# Generated by Django 5.2.13 on 2026-08-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_credit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18),
        ),
    ]
