# Generated by Django 5.0.4 on 2026-09-09 05:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_invoice_payment_destination_and_more'),
        ('customers', '0004_alter_customer_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCreditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('log_type', models.CharField(choices=[('LIMIT_CHANGE', 'Credit Limit Change'), ('PREPAID_DEPOSIT', 'Prepaid Advance Deposit'), ('PREPAID_USAGE', 'Prepaid Balance Used'), ('PREPAID_REFUND', 'Prepaid Balance Refunded'), ('SETTLEMENT', 'Credit Due Settle')], db_index=True, max_length=20)),
                ('old_amount', models.DecimalField(decimal_places=2, default=0, help_text='Balance or limit before this change', max_digits=18)),
                ('new_amount', models.DecimalField(decimal_places=2, default=0, help_text='Balance or limit after this change', max_digits=18)),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, help_text='Delta amount (+/-)', max_digits=18)),
                ('payment_mode', models.CharField(blank=True, help_text='CASH, STAFF_UPI, SHOP_UPI', max_length=20)),
                ('payment_destination', models.CharField(blank=True, help_text='STAFF (staff wallet) or SHOP (shop account)', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_customer_credit_logs', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_logs', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_credit_logs', to='billing.invoice')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Credit Log',
                'verbose_name_plural': 'Customer Credit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'log_type', '-created_at'], name='customers_c_custome_a77571_idx')],
            },
        ),
    ]
