# Generated by Django 5.2.13 on 2026-08-11 20:01

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customer_credit_balance'),
        ('employees', '0005_alter_wallettransaction_category'),
        ('finance', '0004_alter_cashbookentry_category'),
        ('services', '0003_servicecategory_custom_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('reference_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('entry_date', models.DateField(db_index=True, default=datetime.date.today)),
                ('customer_name', models.CharField(blank=True, db_index=True, max_length=150)),
                ('page_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('charged_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CUSTOMER_CREDIT', 'Customer Credit')], db_index=True, default='CASH', max_length=20)),
                ('credit_rest_mode', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer')], help_text='How the unpaid rest of a customer-credit bill is collected.', max_length=20)),
                ('transfer_to_customer', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('transfer_on_behalf', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cash_withdrawal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit_used', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('income', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SAVED', 'Saved')], db_index=True, default='DRAFT', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('bank_account', models.ForeignKey(blank=True, help_text='Shop bank / UPI account that receives online payments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Optional; walk-in work may leave this blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_entries', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Staff member who did the work (auto-filled from the login).', on_delete=django.db.models.deletion.PROTECT, related_name='work_entries', to='employees.employee')),
                ('service', models.ForeignKey(help_text='Work type / service from the catalog.', on_delete=django.db.models.deletion.PROTECT, related_name='work_entries', to='services.service')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Entry',
                'verbose_name_plural': 'Work Entries',
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'entry_date'], name='workentry_w_employe_913c0c_idx'), models.Index(fields=['status', 'entry_date'], name='workentry_w_status_038d0b_idx')],
            },
        ),
    ]
