# Generated by Django 5.2.13 on 2026-08-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoicelinefieldvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(blank=True, db_index=True, help_text='Snapshot of the customer name for walk-in bills without a linked customer record.', max_length=150),
        ),
    ]
