# Generated by Django 5.2.13 on 2026-08-10 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_customer_name'),
        ('finance', '0004_alter_cashbookentry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Bank / UPI account that received this payment (for non-cash modes).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_payments', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='bank_transaction',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.banktransaction'),
        ),
    ]
