# Generated by Django 5.2.13 on 2026-08-17 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoicepayment_bank_account_and_more'),
        ('employees', '0005_alter_wallettransaction_category'),
        ('finance', '0004_alter_cashbookentry_category'),
        ('services', '0004_service_income_formula_service_passthrough_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='related_reference',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='bank_transaction',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.banktransaction'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='cash_entry',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.cashbookentry'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='income_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='wallet_entry',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.wallettransaction'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT', 'Credit / On Account'), ('CUSTOMER_WALLET', 'Customer Wallet (credit balance)')], db_index=True, default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicelinefieldvalue',
            name='field',
            field=models.ForeignKey(blank=True, help_text='Null for migrated / formula-only values without a live custom-field definition.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='services.servicecustomfield'),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT', 'Credit / On Account'), ('CUSTOMER_WALLET', 'Customer Wallet (credit balance)')], max_length=20),
        ),
    ]
