# Generated by Django 5.0.4 on 2026-09-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_link_imported_work_entry_cash_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_destination',
            field=models.CharField(choices=[('SHOP', 'Shop Account (Shop QR / Main Galla)'), ('STAFF', 'Staff Wallet (Staff UPI / Counter Float)')], db_index=True, default='SHOP', help_text='Whether payment was received into shop accounts (Shop QR/Galla) or staff wallet (Staff UPI/Hand).', max_length=10),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='payment_destination',
            field=models.CharField(choices=[('SHOP', 'Shop Account (Shop QR / Main Galla)'), ('STAFF', 'Staff Wallet (Staff UPI / Counter Float)')], default='SHOP', help_text='Whether payment was received into shop accounts (Shop QR/Galla) or staff wallet (Staff UPI/Hand).', max_length=10),
        ),
    ]
