# Generated by Django 5.0.4 on 2026-09-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_invoice_payment_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_destination',
            field=models.CharField(choices=[('AUTO', 'Smart Auto (Cash to Staff, UPI to Shop QR)'), ('STAFF', 'Staff Wallet (Both Cash & UPI to Staff)'), ('SHOP', 'Shop Account (Cash to Main Galla, UPI to Shop QR)')], db_index=True, default='AUTO', help_text='Whether payment was received into shop accounts (Shop QR/Galla) or staff wallet (Staff UPI/Hand).', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='payment_destination',
            field=models.CharField(choices=[('AUTO', 'Smart Auto (Cash to Staff, UPI to Shop QR)'), ('STAFF', 'Staff Wallet (Both Cash & UPI to Staff)'), ('SHOP', 'Shop Account (Cash to Main Galla, UPI to Shop QR)')], default='AUTO', help_text='Whether payment was received into shop accounts (Shop QR/Galla) or staff wallet (Staff UPI/Hand).', max_length=10),
        ),
    ]
