# Generated by Django 5.2.13 on 2026-08-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, choices=[('GAMES', 'Games'), ('INTERNET', 'Internet'), ('PRINTING', 'Printing'), ('RECHARGE', 'Recharge'), ('SNACKS', 'Snacks'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30),
        ),
    ]
