# Generated by Django 5.2.13 on 2026-08-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicecategory_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='income_formula',
            field=models.CharField(blank=True, help_text='Optional formula for what the shop keeps. Leave blank to keep the whole line amount.', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='passthrough_type',
            field=models.CharField(choices=[('NONE', 'None (plain sale)'), ('CASH', 'Cash given to customer (withdrawal / E-Sathi)'), ('ONLINE', 'Online transfer on behalf of customer')], default='NONE', help_text='How pass-through money leaves the shop when this service is billed.', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='total_formula',
            field=models.CharField(blank=True, help_text='Optional formula for what the customer is charged. Uses field variables, qty, price. Leave blank for qty × price.', max_length=255),
        ),
        migrations.AddField(
            model_name='servicecustomfield',
            name='variable_name',
            field=models.CharField(blank=True, db_index=True, help_text="Machine name used inside service formulas, e.g. 'cash_amount'. Auto-generated from the label when left blank.", max_length=50),
        ),
    ]
