# Generated by Django 5.0.4 on 2026-09-03 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_bankaccount_is_default'),
        ('services', '0004_service_income_formula_service_passthrough_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='default_bank_account',
            field=models.ForeignKey(blank=True, help_text='Default/dedicated bank account for this service (e.g. AEPS CBI account)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='finance.bankaccount'),
        ),
    ]
