# Generated by Django 5.2.13 on 2026-08-02 10:50

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('account_name', models.CharField(max_length=150)),
                ('bank_name', models.CharField(max_length=150)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('account_type', models.CharField(choices=[('CURRENT', 'Current Account'), ('SAVINGS', 'Savings Account'), ('CASH_CREDIT', 'Cash Credit / Overdraft')], default='CURRENT', max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['account_name'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Deposit / Credit'), ('DEBIT', 'Withdrawal / Debit')], db_index=True, max_length=10)),
                ('category', models.CharField(choices=[('DEPOSIT', 'Cash / Cheque Deposit'), ('WITHDRAWAL', 'Cash Withdrawal'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('PAYMENT_RECEIVED', 'Payment Received'), ('EXPENSE_PAYMENT', 'Expense Payment'), ('SALARY', 'Salary Payment'), ('INTEREST', 'Interest Earned'), ('CHARGES', 'Bank Charges'), ('MISC', 'Miscellaneous')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance_after', models.DecimalField(decimal_places=2, editable=False, max_digits=18)),
                ('reference_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('related_reference', models.CharField(blank=True, editable=False, help_text='Reference of the paired transaction (e.g. bank-to-bank transfer).', max_length=30)),
                ('party_name', models.CharField(blank=True, help_text='Counterparty: who deposited or was paid.', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('entry_date', models.DateField(db_index=True, default=datetime.date.today)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Transaction',
                'verbose_name_plural': 'Bank Transactions',
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['account', 'entry_date'], name='finance_ban_account_2f74c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='CashBookEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('entry_date', models.DateField(db_index=True, default=datetime.date.today)),
                ('entry_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], db_index=True, max_length=10)),
                ('category', models.CharField(choices=[('SALES', 'Sales'), ('SERVICE_FEE', 'Service Fee'), ('OTHER_INCOME', 'Other Income'), ('PURCHASE', 'Purchases'), ('RENT', 'Rent'), ('ELECTRICITY', 'Electricity'), ('INTERNET', 'Internet / ISP'), ('SALARY', 'Salary'), ('MAINTENANCE', 'Maintenance'), ('UTILITIES', 'Utilities'), ('TAX', 'Tax'), ('MISC', 'Miscellaneous')], max_length=30)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer')], db_index=True, default='CASH', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('party_name', models.CharField(blank=True, help_text='Who we received from / paid to (customer, vendor, party).', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Book Entry',
                'verbose_name_plural': 'Cash Book Entries',
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['entry_date', 'entry_type'], name='finance_cas_entry_d_8fd5a7_idx')],
            },
        ),
    ]
