# Generated by Django 5.2.13 on 2026-08-06 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_hourly_rate_worklogentry'),
        ('finance', '0002_alter_cashbookentry_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbookentry',
            options={'ordering': ['-entry_date', '-created_at'], 'permissions': [('add_cashbookincome', 'Can add cash book income entries'), ('add_cashbookexpense', 'Can add cash book expense entries'), ('withdraw_shop_cash', 'Can withdraw cash from the shop cash book')], 'verbose_name': 'Cash Book Entry', 'verbose_name_plural': 'Cash Book Entries'},
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='Responsible staff member — the entry is maintained in their cash book.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='cashbookentry',
            name='category',
            field=models.CharField(choices=[('SALES', 'Sales'), ('SERVICE_FEE', 'Service Fee'), ('COMMISSION', 'Commission / E-Sathi'), ('OTHER_INCOME', 'Other Income'), ('OWNER_DEPOSIT', 'Owner Deposit'), ('PURCHASE', 'Purchases'), ('RENT', 'Rent'), ('ELECTRICITY', 'Electricity'), ('INTERNET', 'Internet / ISP'), ('SALARY', 'Salary'), ('MAINTENANCE', 'Maintenance'), ('UTILITIES', 'Utilities'), ('TAX', 'Tax'), ('CASH_OUT', 'Cash Out / E-Sathi'), ('OWNER_WITHDRAWAL', 'Owner Withdrawal'), ('MISC', 'Miscellaneous')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='cashbookentry',
            index=models.Index(fields=['staff', 'entry_date'], name='finance_cas_staff_i_b15a0e_idx'),
        ),
    ]
