# Generated by Django 5.2.13 on 2026-08-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_cashbookentry_options_cashbookentry_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbookentry',
            name='category',
            field=models.CharField(choices=[('SALES', 'Sales'), ('SERVICE_FEE', 'Service Fee'), ('COMMISSION', 'Commission / E-Sathi'), ('OTHER_INCOME', 'Other Income'), ('OWNER_DEPOSIT', 'Owner Deposit'), ('PURCHASE', 'Purchases'), ('RENT', 'Rent'), ('ELECTRICITY', 'Electricity'), ('INTERNET', 'Internet / ISP'), ('SALARY', 'Salary'), ('MAINTENANCE', 'Maintenance'), ('UTILITIES', 'Utilities'), ('TAX', 'Tax'), ('CASH_OUT', 'Cash Out / E-Sathi'), ('ADVANCE', 'Advance / Staff Float'), ('OWNER_WITHDRAWAL', 'Owner Withdrawal'), ('MISC', 'Miscellaneous')], max_length=30),
        ),
    ]
