# Generated by Django 5.0.4 on 2026-09-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_cashbookentry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default shop bank account for general UPI QR and online payments'),
        ),
    ]
