# Generated by Django 5.0.4 on 2026-09-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_bankaccount_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbookentry',
            name='category',
            field=models.CharField(choices=[('SALES', 'Sales'), ('SERVICE_FEE', 'Service Fee'), ('COMMISSION', 'Commission / E-Sathi'), ('OTHER_INCOME', 'Other Income'), ('OWNER_DEPOSIT', 'Owner Deposit'), ('FLOAT_IN', 'Staff Float In (Float Returned)'), ('PURCHASE', 'Purchases'), ('RENT', 'Rent'), ('ELECTRICITY', 'Electricity'), ('INTERNET', 'Internet / ISP'), ('SALARY', 'Salary'), ('MAINTENANCE', 'Maintenance'), ('UTILITIES', 'Utilities'), ('TAX', 'Tax'), ('CASH_OUT', 'Cash Out / E-Sathi'), ('ADVANCE', 'Salary Advance'), ('FLOAT_OUT', 'Staff Float Out (Counter Float)'), ('OWNER_WITHDRAWAL', 'Owner Withdrawal'), ('MISC', 'Miscellaneous')], max_length=30),
        ),
    ]
