# Generated by Django 5.0.4 on 2026-09-06 05:59

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_wallettransaction_category'),
        ('finance', '0006_alter_cashbookentry_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbookentry',
            name='category',
            field=models.CharField(choices=[('SALES', 'Sales'), ('SERVICE_FEE', 'Service Fee'), ('COMMISSION', 'Commission / E-Sathi'), ('OTHER_INCOME', 'Other Income'), ('OWNER_DEPOSIT', 'Owner Deposit'), ('FLOAT_IN', 'Staff Float In (Float Returned)'), ('PURCHASE', 'Purchases'), ('RENT', 'Rent'), ('ELECTRICITY', 'Electricity'), ('INTERNET', 'Internet / ISP'), ('SALARY', 'Salary'), ('MAINTENANCE', 'Maintenance'), ('UTILITIES', 'Utilities'), ('TAX', 'Tax'), ('CASH_OUT', 'Cash Out / E-Sathi'), ('ADVANCE', 'Salary Advance'), ('FLOAT_OUT', 'Staff Float Out (Counter Float)'), ('REIMBURSEMENT', 'Cash Float Reimbursement'), ('OWNER_WITHDRAWAL', 'Owner Withdrawal'), ('MISC', 'Miscellaneous')], max_length=30),
        ),
        migrations.CreateModel(
            name='UPIBookEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('entry_date', models.DateField(db_index=True, default=datetime.date.today)),
                ('entry_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], db_index=True, max_length=10)),
                ('category', models.CharField(choices=[('SALES', 'Sales'), ('SERVICE_FEE', 'Service Fee'), ('COMMISSION', 'Commission / E-Sathi'), ('OTHER_INCOME', 'Other Income'), ('OWNER_DEPOSIT', 'Owner Deposit'), ('FLOAT_IN', 'Staff Float In (Float Returned)'), ('PURCHASE', 'Purchases'), ('RENT', 'Rent'), ('ELECTRICITY', 'Electricity'), ('INTERNET', 'Internet / ISP'), ('SALARY', 'Salary'), ('MAINTENANCE', 'Maintenance'), ('UTILITIES', 'Utilities'), ('TAX', 'Tax'), ('CASH_OUT', 'Cash Out / E-Sathi'), ('ADVANCE', 'Salary Advance'), ('FLOAT_OUT', 'Staff Float Out (Counter Float)'), ('REIMBURSEMENT', 'Cash Float Reimbursement'), ('OWNER_WITHDRAWAL', 'Owner Withdrawal'), ('MISC', 'Miscellaneous')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('party_name', models.CharField(blank=True, help_text='Customer / Vendor / UPI App / Staff.', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('bank_account', models.ForeignKey(blank=True, help_text='Linked bank account for float funding, customer deposits, or sweeps.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upi_entries', to='finance.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, help_text='Responsible staff member if entry is assigned to or handled by staff.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upi_entries', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UPI Book Entry',
                'verbose_name_plural': 'UPI Book Entries',
                'ordering': ['-entry_date', '-created_at'],
                'permissions': [('withdraw_shop_upi', 'Can withdraw / sweep UPI float from the shop UPI book')],
                'indexes': [models.Index(fields=['entry_date', 'entry_type'], name='finance_upi_entry_d_6d978d_idx'), models.Index(fields=['staff', 'entry_date'], name='finance_upi_staff_i_e47e9a_idx')],
            },
        ),
    ]
