"""
EmployeeSelector — read-only access to Employee data.

Views and templates go through these helpers so that query optimisation
(select_related) and filtering rules live in one place.
"""
from datetime import date
from decimal import Decimal
from django.contrib.auth import get_user_model
from django.db.models import Sum

from apps.employees.models import Employee

User = get_user_model()


class EmployeeSelector:
    @staticmethod
    def list_active():
        return Employee.objects.select_related("user").order_by("-created_at")

    @staticmethod
    def get_by_id(employee_id):
        return Employee.objects.select_related("user").filter(id=employee_id).first()

    @staticmethod
    def get_by_user(user):
        return Employee.objects.select_related("user").filter(user=user).first()

    @staticmethod
    def by_role(role):
        return Employee.objects.filter(role=role)

    @staticmethod
    def count_active() -> int:
        return Employee.objects.count()

    @staticmethod
    def count_users() -> int:
        return User.objects.filter(is_active=True).count()

    @staticmethod
    def get_income_stats(employee):
        """
        Calculate income generated by this staff member's created invoices.
        Authoritative shop profit/income vs pass-through funds.
        """
        empty_stats = {
            "today_income": Decimal("0.00"),
            "today_billed": Decimal("0.00"),
            "today_bills_count": 0,
            "month_income": Decimal("0.00"),
            "month_billed": Decimal("0.00"),
            "month_bills_count": 0,
            "total_income": Decimal("0.00"),
            "total_billed": Decimal("0.00"),
            "total_bills_count": 0,
            "recent_invoices": [],
        }
        if not employee or not employee.user:
            return empty_stats

        try:
            from apps.billing.models import Invoice, InvoiceLine
        except ImportError:
            return empty_stats

        today = date.today()
        month_start = date(today.year, today.month, 1)

        user_invoices = Invoice.objects.filter(created_by=employee.user, is_active=True)
        user_lines = InvoiceLine.objects.filter(
            invoice__created_by=employee.user,
            invoice__is_active=True,
            is_active=True,
        )

        today_invoices = user_invoices.filter(billed_on=today)
        today_lines = user_lines.filter(invoice__billed_on=today)
        today_income = today_lines.aggregate(s=Sum("income_amount"))["s"] or Decimal("0.00")
        today_billed = today_invoices.aggregate(s=Sum("total"))["s"] or Decimal("0.00")
        today_bills_count = today_invoices.count()

        month_invoices = user_invoices.filter(billed_on__gte=month_start)
        month_lines = user_lines.filter(invoice__billed_on__gte=month_start)
        month_income = month_lines.aggregate(s=Sum("income_amount"))["s"] or Decimal("0.00")
        month_billed = month_invoices.aggregate(s=Sum("total"))["s"] or Decimal("0.00")
        month_bills_count = month_invoices.count()

        total_income = user_lines.aggregate(s=Sum("income_amount"))["s"] or Decimal("0.00")
        total_billed = user_invoices.aggregate(s=Sum("total"))["s"] or Decimal("0.00")
        total_bills_count = user_invoices.count()

        recent_invoices = list(
            user_invoices.select_related("customer")
            .prefetch_related("lines")
            .order_by("-billed_on", "-created_at")[:15]
        )

        return {
            "today_income": today_income,
            "today_billed": today_billed,
            "today_bills_count": today_bills_count,
            "month_income": month_income,
            "month_billed": month_billed,
            "month_bills_count": month_bills_count,
            "total_income": total_income,
            "total_billed": total_billed,
            "total_bills_count": total_bills_count,
            "recent_invoices": recent_invoices,
        }

