# Generated by Django 5.0.4 on 2026-08-21 22:19

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_alter_wallettransaction_category'),
        ('finance', '0004_alter_cashbookentry_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('sku', models.CharField(blank=True, help_text='Optional SKU or barcode.', max_length=50, null=True, unique=True)),
                ('category', models.CharField(blank=True, db_index=True, help_text='Free-form category, e.g. Paper, Ink, Snacks.', max_length=50)),
                ('unit', models.CharField(choices=[('PIECE', 'Piece'), ('PACK', 'Pack'), ('REAM', 'Ream'), ('BOX', 'Box'), ('KG', 'Kilogram'), ('LITRE', 'Litre'), ('METRE', 'Metre'), ('OTHER', 'Other')], default='PIECE', max_length=20)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, help_text='Current quantity in stock. Updated on every movement.', max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=5, help_text='Low-stock alert fires when current_stock falls to or below this level.', max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Weighted average cost per unit. Recalculated on every purchase.', max_digits=18)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Item',
                'verbose_name_plural': 'Stock Items',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('reference_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Purchase (Stock In)'), ('ISSUE', 'Issued (Stock Out)'), ('ADJUSTMENT', 'Adjustment'), ('DAMAGE', 'Damaged / Wasted'), ('RETURN', 'Return to Supplier')], db_index=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Always positive; direction is inferred from movement_type.', max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit at this movement.', max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='quantity × unit_cost.', max_digits=18)),
                ('movement_date', models.DateField(db_index=True, default=datetime.date.today)),
                ('supplier_name', models.CharField(blank=True, help_text='Supplier / vendor name (for purchases).', max_length=150)),
                ('reason', models.CharField(blank=True, help_text="Reason or note, e.g. 'Issued to Counter 1', 'Damaged in transit'.", max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('cash_entry', models.ForeignKey(blank=True, help_text='Linked cash book expense for purchase movements.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='finance.cashbookentry')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockitem')),
                ('staff', models.ForeignKey(blank=True, help_text='Staff member who handled this movement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['category', 'name'], name='inventory_s_categor_aee61a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['current_stock', 'reorder_level'], name='inventory_s_current_e411ac_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', 'movement_date'], name='inventory_s_item_id_c55b35_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'movement_date'], name='inventory_s_movemen_86911f_idx'),
        ),
    ]
