# Generated by Django 5.2.13 on 2026-08-02 10:50

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(help_text='The employee this wallet belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], db_index=True, max_length=10)),
                ('category', models.CharField(choices=[('CASH_TOPUP', 'Cash Top-up'), ('CASH_WITHDRAWAL', 'Cash Withdrawal'), ('SALARY', 'Salary Payment'), ('ADVANCE', 'Advance'), ('BONUS', 'Bonus'), ('PENALTY', 'Penalty'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('PAYMENT_COLLECTED', 'Payment Collected'), ('EXPENSE', 'Expense'), ('ADJUSTMENT', 'Adjustment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance_after', models.DecimalField(decimal_places=2, editable=False, max_digits=18)),
                ('reference_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('related_reference', models.CharField(blank=True, editable=False, help_text='Reference of the paired transaction (e.g. wallet-to-wallet transfer).', max_length=30)),
                ('source', models.CharField(blank=True, help_text='Where the money came from.', max_length=150)),
                ('destination', models.CharField(blank=True, help_text='Where the money went.', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('entry_date', models.DateField(db_index=True, default=datetime.date.today)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='employees.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['wallet', 'entry_date'], name='employees_w_wallet__bdf5f6_idx')],
            },
        ),
    ]
