# Generated by Django 5.2.13 on 2026-08-10 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_hourly_rate_worklogentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online / UPI')], db_index=True, default='CASH', help_text='CASH float or ONLINE / UPI collections wallet.', max_length=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='employee',
            field=models.ForeignKey(help_text='The employee this wallet belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='category',
            field=models.CharField(choices=[('CASH_TOPUP', 'Cash Top-up'), ('CASH_WITHDRAWAL', 'Cash Withdrawal'), ('SALARY', 'Salary Payment'), ('ADVANCE', 'Advance'), ('BONUS', 'Bonus'), ('PENALTY', 'Penalty'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('PAYMENT_COLLECTED', 'Payment Collected'), ('CASH_GIVEN', 'Cash Given to Customer'), ('EXPENSE', 'Expense'), ('ADJUSTMENT', 'Adjustment')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('employee', 'wallet_type'), name='unique_wallet_per_employee_and_type'),
        ),
    ]
