# Generated by Django 5.2.13 on 2026-08-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_wallet_wallet_type_alter_wallet_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='category',
            field=models.CharField(choices=[('CASH_TOPUP', 'Cash Top-up'), ('CASH_WITHDRAWAL', 'Cash Withdrawal'), ('SALARY', 'Salary Payment'), ('ADVANCE', 'Advance'), ('BONUS', 'Bonus'), ('PENALTY', 'Penalty'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('PAYMENT_COLLECTED', 'Payment Collected'), ('CASH_GIVEN', 'Cash Given to Customer'), ('PAYOUT', 'Customer Payout / Transfer'), ('EXPENSE', 'Expense'), ('ADJUSTMENT', 'Adjustment')], max_length=30),
        ),
    ]
