# Generated by Django 5.0.4 on 2026-09-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_wallettransaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_create_bills',
            field=models.BooleanField(db_index=True, default=False, help_text='Grant counter billing & invoice creation access regardless of base role.'),
        ),
    ]
