# Generated by Django 5.0.4 on 2026-09-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_can_create_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_manage_topup',
            field=models.BooleanField(db_index=True, default=False, help_text='Grant permission to perform wallet top-ups and owner cash deposit/withdrawal.'),
        ),
    ]
