# Generated by Django 5.0.4 on 2026-09-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_can_manage_topup'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_collect_personal_upi',
            field=models.BooleanField(db_index=True, default=False, help_text='Allow staff to collect payments into their personal Staff UPI/Wallet during rush hours.'),
        ),
    ]
