# Generated by Django 5.0.4 on 2026-09-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_can_collect_personal_upi'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_record_expenses',
            field=models.BooleanField(db_index=True, default=False, help_text='Allow staff to record shop expenses from counter float or shop bank account.'),
        ),
    ]
