# Generated by Django 5.0.4 on 2026-09-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_can_record_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='category',
            field=models.CharField(choices=[('CASH_TOPUP', 'Cash Top-up'), ('CASH_WITHDRAWAL', 'Cash Withdrawal'), ('SALARY', 'Salary Payment'), ('ADVANCE', 'Advance'), ('BONUS', 'Bonus'), ('PENALTY', 'Penalty'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('PAYMENT_COLLECTED', 'Payment Collected'), ('CASH_GIVEN', 'Cash Given to Customer'), ('PAYOUT', 'Customer Payout / Transfer'), ('EXPENSE', 'Expense'), ('ADJUSTMENT', 'Adjustment'), ('FLOAT_IN', 'Daily Float Received'), ('FLOAT_OUT', 'Daily Float Returned')], max_length=30),
        ),
    ]
