# Generated by Django 5.0.4 on 2026-09-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_wallettransaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_view_shop_finance',
            field=models.BooleanField(db_index=True, default=False, help_text='Allow staff to view Entire Shop Main Galla & Shop UPI Book.'),
        ),
    ]
