# Generated by Django 5.0.4 on 2026-09-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employee_can_view_shop_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_manage_permissions',
            field=models.BooleanField(db_index=True, default=False, help_text='Grant permission to assign and modify permissions for other employees.'),
        ),
    ]
