# Generated by Django 5.0.4 on 2026-09-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employee_can_manage_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_manage_customer_credit',
            field=models.BooleanField(db_index=True, default=False, help_text='Grant permission to set and modify customer credit limits.'),
        ),
    ]
